name: Release

# on:
#   release:
#     types: [created]
on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine poetry
        poetry install

    - name: Get the version from the tag
      id: get_version
      run: echo "::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}"

    - name: Update version in pyproject.toml
      run: |
        version=${{ steps.get_version.outputs.VERSION }}
        poetry version $version

    - name: Build a binary wheel and a source tarball
      run: poetry build

    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages-dir: dist